### ISSUE TITLE
Script gets stuck due to error when attempting to scroll down to oldest comment

### ISSUE THREAD

**Issue by Derpitron** [fonic/YouTube-Activity-Cleaner#1]
I followed the given instructions.

However when I try to Right Click -> Tampermonkey -> Youtube Comment Cleaner (YCC), nothing happens. No popup, no alert, nothing at all on the page.

![image](https://github.com/fonic/Youtube-Comment-Cleaner/assets/46134462/3ee62d7b-1a4f-4ab7-b552-25f979d69dc8)

**Comment by fonic** [comment]
Please provide the full URL from the browser bar of the page you try to run this on. The script only works with specific URLs (which are hard-coded within the script; a limitation of the original this was forked from).

**Comment by Derpitron** [comment]
https://myactivity.google.com/page?hl=en&utm_medium=web&utm_source=youtube&page=youtube_comments

I also noticed the script keeps constantly scrolling down to load new comments. Is this intended and expected?

**Comment by fonic** [comment]
> https://myactivity.google.com/page?hl=en&utm_medium=web&utm_source=youtube&page=youtube_comments
> 
> I also noticed the script keeps constantly scrolling down to load new comments. Is this intended and expected?

Yes. So it actually **does** work, you simply were a bit to impatient ;)

**Comment by Derpitron** [comment]
![image](https://github.com/fonic/Youtube-Comment-Cleaner/assets/46134462/1e1ef0b7-c067-4aad-916a-16673cc1a75e)
Seems to say Unable to Load more. Clicking the retry option loads for a second, then shows the same error. No comment entries are loading after this.

**Comment by fonic** [comment]
> Seems to say Unable to Load more. Clicking the retry option loads for a second, then shows the same error. No comment entries are loading after this.

That seems to be an issue with Google or your specific setup then. The script just tries to scroll down to the very end and then starts deletion. You could ask the [original author of the script](https://gist.github.com/cprima/2f7ea8e353c18a666506021c85e9773d) if they ever encountered that error.

**Comment by fonic** [comment]
> Seems to say Unable to Load more. Clicking the retry option loads for a second, then shows the same error. No comment entries are loading after this.

That seems to be an issue with Google, your specific account or your specific setup then. The script just tries to scroll down to the very end (i.e. to the oldest comment) and then starts deletion from oldest to newest.

You could ask the [original author of the script](https://gist.github.com/cprima/2f7ea8e353c18a666506021c85e9773d) if they ever encountered that kind of error.

**Comment by Derpitron** [comment]
Let me know if you ever manage to duplicate it on your end then. Closing for now

**Comment by fonic** [comment]
> Let me know if you ever manage to duplicate it on your end then. Closing for now

Sure will. Haven't seen that error myself, but I don't have accounts with lots of comments to test with.

**Comment by fonic** [comment]
Fixed in version 1.5 (commit 40f97909bf7906be104162f1a603f7ad48d11992).

**Comment by fonic** [comment]
Fixed in version 1.5 (commit 40f97909bf7906be104162f1a603f7ad48d11992).

**Comment by fonic** [comment]
Fixed in version 1.5 (commit 40f97909bf7906be104162f1a603f7ad48d11992).
